programming/RaceTrack/grails-app/domain/racetrack/Runner.groovy
package racetrack

class Runner {

    static constraints = {
        firstName(blank:false)
        lastName(blank:false)
        dateOfBirth()
        gender(inList:["M", "F"])
        address()
        city()
        state()
        zipcode()
        email(email:true)
    }
    static hasMany = [registrations:Registration]

    String firstName
    String lastName
    Date dateOfBirth
    String gender
    String address
    String city
    String state
    String zipcode
    String email

    String toString(){
        "${lastName}, ${firstName} (${email})"
    }

}

programming/RaceTrack/grails-app/controllers/racetrack/RegistrationController.groovy
package racetrack

class RegistrationController {

    def scaffold = true

    //def index() {}
}

programming/RaceTrack/grails-app/controllers/racetrack/RunnerController.groovy
package racetrack

class RunnerController {

    def scaffold = true
}

programming/RaceTrack/grails-app/views/runner/_form.gsp
<%@ page import="racetrack.Runner" %>



<div class="fieldcontain ${hasErrors(bean: runnerInstance, field: 'firstName', 'error')} required">
    <label for="firstName">
        <g:message code="runner.firstName.label" default="First Name"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="firstName" required="" value="${runnerInstance?.firstName}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: runnerInstance, field: 'lastName', 'error')} required">
    <label for="lastName">
        <g:message code="runner.lastName.label" default="Last Name"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="lastName" required="" value="${runnerInstance?.lastName}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: runnerInstance, field: 'dateOfBirth', 'error')} required">
    <label for="dateOfBirth">
        <g:message code="runner.dateOfBirth.label" default="Date Of Birth"/>
        <span class="required-indicator">*</span>
    </label>
    <g:datePicker name="dateOfBirth" precision="day" value="${runnerInstance?.dateOfBirth}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: runnerInstance, field: 'gender', 'error')} ">
    <label for="gender">
        <g:message code="runner.gender.label" default="Gender"/>

    </label>
    <g:select name="gender" from="${runnerInstance.constraints.gender.inList}" value="${runnerInstance?.gender}"
              valueMessagePrefix="runner.gender" noSelection="['': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: runnerInstance, field: 'address', 'error')} ">
    <label for="address">
        <g:message code="runner.address.label" default="Address"/>

    </label>
    <g:textField name="address" value="${runnerInstance?.address}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: runnerInstance, field: 'city', 'error')} ">
    <label for="city">
        <g:message code="runner.city.label" default="City"/>

    </label>
    <g:textField name="city" value="${runnerInstance?.city}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: runnerInstance, field: 'state', 'error')} ">
    <label for="state">
        <g:message code="runner.state.label" default="State"/>

    </label>
    <g:textField name="state" value="${runnerInstance?.state}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: runnerInstance, field: 'zipcode', 'error')} ">
    <label for="zipcode">
        <g:message code="runner.zipcode.label" default="Zipcode"/>

    </label>
    <g:textField name="zipcode" value="${runnerInstance?.zipcode}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: runnerInstance, field: 'email', 'error')} ">
    <label for="email">
        <g:message code="runner.email.label" default="Email"/>

    </label>
    <g:field type="email" name="email" value="${runnerInstance?.email}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: runnerInstance, field: 'registrations', 'error')} ">
    <label for="registrations">
        <g:message code="runner.registrations.label" default="Registrations"/>

    </label>

    <ul class="one-to-many">
        <g:each in="${runnerInstance?.registrations ?}" var="r">
            <li><g:link controller="registration" action="show" id="${r.id}">${r?.encodeAsHTML()}</g:link></li>
        </g:each>
        <li class="add">
            <g:link controller="registration" action="create"
                    params="['runner.id': runnerInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'registration.label', default: 'Registration')])}</g:link>
        </li>
    </ul>

</div>

programming/RaceTrack/grails-app/views/runner/create.gsp
<%@ page import="racetrack.Runner" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'runner.label', default: 'Runner')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-runner" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                               default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-runner" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${runnerInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${runnerInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form action="save">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

programming/RaceTrack/grails-app/views/runner/edit.gsp
<%@ page import="racetrack.Runner" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'runner.label', default: 'Runner')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-runner" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                             default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-runner" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${runnerInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${runnerInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form method="post">
        <g:hiddenField name="id" value="${runnerInstance?.id}"/>
        <g:hiddenField name="version" value="${runnerInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate=""
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

programming/RaceTrack/grails-app/views/runner/list.gsp
<%@ page import="racetrack.Runner" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'runner.label', default: 'Runner')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-runner" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                             default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-runner" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="firstName"
                              title="${message(code: 'runner.firstName.label', default: 'First Name')}"/>

            <g:sortableColumn property="lastName"
                              title="${message(code: 'runner.lastName.label', default: 'Last Name')}"/>

            <g:sortableColumn property="dateOfBirth"
                              title="${message(code: 'runner.dateOfBirth.label', default: 'Date Of Birth')}"/>

            <g:sortableColumn property="gender" title="${message(code: 'runner.gender.label', default: 'Gender')}"/>

            <g:sortableColumn property="address" title="${message(code: 'runner.address.label', default: 'Address')}"/>

            <g:sortableColumn property="city" title="${message(code: 'runner.city.label', default: 'City')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${runnerInstanceList}" status="i" var="runnerInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show"
                            id="${runnerInstance.id}">${fieldValue(bean: runnerInstance, field: "firstName")}</g:link></td>

                <td>${fieldValue(bean: runnerInstance, field: "lastName")}</td>

                <td><g:formatDate date="${runnerInstance.dateOfBirth}"/></td>

                <td>${fieldValue(bean: runnerInstance, field: "gender")}</td>

                <td>${fieldValue(bean: runnerInstance, field: "address")}</td>

                <td>${fieldValue(bean: runnerInstance, field: "city")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${runnerInstanceTotal}"/>
    </div>
</div>
</body>
</html>

programming/RaceTrack/grails-app/views/runner/show.gsp
<%@ page import="racetrack.Runner" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'runner.label', default: 'Runner')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-runner" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                             default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-runner" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list runner">

        <g:if test="${runnerInstance?.firstName}">
            <li class="fieldcontain">
                <span id="firstName-label" class="property-label"><g:message code="runner.firstName.label"
                                                                             default="First Name"/></span>

                <span class="property-value" aria-labelledby="firstName-label"><g:fieldValue bean="${runnerInstance}"
                                                                                             field="firstName"/></span>

            </li>
        </g:if>

        <g:if test="${runnerInstance?.lastName}">
            <li class="fieldcontain">
                <span id="lastName-label" class="property-label"><g:message code="runner.lastName.label"
                                                                            default="Last Name"/></span>

                <span class="property-value" aria-labelledby="lastName-label"><g:fieldValue bean="${runnerInstance}"
                                                                                            field="lastName"/></span>

            </li>
        </g:if>

        <g:if test="${runnerInstance?.dateOfBirth}">
            <li class="fieldcontain">
                <span id="dateOfBirth-label" class="property-label"><g:message code="runner.dateOfBirth.label"
                                                                               default="Date Of Birth"/></span>

                <span class="property-value" aria-labelledby="dateOfBirth-label"><g:formatDate
                        date="${runnerInstance?.dateOfBirth}"/></span>

            </li>
        </g:if>

        <g:if test="${runnerInstance?.gender}">
            <li class="fieldcontain">
                <span id="gender-label" class="property-label"><g:message code="runner.gender.label"
                                                                          default="Gender"/></span>

                <span class="property-value" aria-labelledby="gender-label"><g:fieldValue bean="${runnerInstance}"
                                                                                          field="gender"/></span>

            </li>
        </g:if>

        <g:if test="${runnerInstance?.address}">
            <li class="fieldcontain">
                <span id="address-label" class="property-label"><g:message code="runner.address.label"
                                                                           default="Address"/></span>

                <span class="property-value" aria-labelledby="address-label"><g:fieldValue bean="${runnerInstance}"
                                                                                           field="address"/></span>

            </li>
        </g:if>

        <g:if test="${runnerInstance?.city}">
            <li class="fieldcontain">
                <span id="city-label" class="property-label"><g:message code="runner.city.label" default="City"/></span>

                <span class="property-value" aria-labelledby="city-label"><g:fieldValue bean="${runnerInstance}"
                                                                                        field="city"/></span>

            </li>
        </g:if>

        <g:if test="${runnerInstance?.state}">
            <li class="fieldcontain">
                <span id="state-label" class="property-label"><g:message code="runner.state.label"
                                                                         default="State"/></span>

                <span class="property-value" aria-labelledby="state-label"><g:fieldValue bean="${runnerInstance}"
                                                                                         field="state"/></span>

            </li>
        </g:if>

        <g:if test="${runnerInstance?.zipcode}">
            <li class="fieldcontain">
                <span id="zipcode-label" class="property-label"><g:message code="runner.zipcode.label"
                                                                           default="Zipcode"/></span>

                <span class="property-value" aria-labelledby="zipcode-label"><g:fieldValue bean="${runnerInstance}"
                                                                                           field="zipcode"/></span>

            </li>
        </g:if>

        <g:if test="${runnerInstance?.email}">
            <li class="fieldcontain">
                <span id="email-label" class="property-label"><g:message code="runner.email.label"
                                                                         default="Email"/></span>

                <span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${runnerInstance}"
                                                                                         field="email"/></span>

            </li>
        </g:if>

        <g:if test="${runnerInstance?.registrations}">
            <li class="fieldcontain">
                <span id="registrations-label" class="property-label"><g:message code="runner.registrations.label"
                                                                                 default="Registrations"/></span>

                <g:each in="${runnerInstance.registrations}" var="r">
                    <span class="property-value" aria-labelledby="registrations-label"><g:link controller="registration"
                                                                                               action="show"
                                                                                               id="${r.id}">${r?.encodeAsHTML()}</g:link></span>
                </g:each>

            </li>
        </g:if>

    </ol>
    <g:form>
        <fieldset class="buttons">
            <g:hiddenField name="id" value="${runnerInstance?.id}"/>
            <g:link class="edit" action="edit" id="${runnerInstance?.id}"><g:message code="default.button.edit.label"
                                                                                     default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>